### ISSUE TITLE
✨feat: 주문 옵션 페이지 개발 (외장, 선택)

### ISSUE THREAD

**Issue by ryungom** [NINI-Bros/GENISISU#3]
## 📏구현 및 수정 기능

- 차량 주문 과정에서 외장 색 선택 옵션 페이지 개발
- 차량 주문 과정에서 선택 옵션 페이지 개발

## 📝 상세 작업 내용
- [x] 외장 옵션 데이터 구조 변경 (통일)
- [x] 외장색 선택 옵션 페이지 개발
    - interior, garnish 와 동일한 컴포넌트로 재사용
- [x] 선택 옵션 페이지 개발
- [x] LocalStorage에 데이터 저장해서 보내주기
- [x] 옵션 페이지 스타일 변경

## 📄 참고 사항
- 선택 옵션 페이지 레퍼런스
![image](https://github.com/user-attachments/assets/55fcec67-1a15-438e-a2a7-0d8e684bb4b7)

**Comment by redcontroller** [comment]
추가로 필요한 기능은 별도 이슈로 만들어서 진행하기에 해당 이슈를 닫습니다.
