### ISSUE TITLE
✨feat: 주문 옵션 페이지의 추가 개발 사항

### ISSUE THREAD

**Issue by ryungom** [NINI-Bros/GENISISU#4]
## 📏구현 및 수정 기능

- 로컬 스토리지 값이 있는 경우 옵션 페이지 기본 설정 값이 바뀌도록 수정
    - 보여지는 이미지가 로컬 스토리지에 저장된 옵션 값이 되도록 함
- LNB 기능 추가 (페이지 이동 시에도 금액 업데이트)
    - 상태관리 툴이 필요할지도 모르겠어요 (zustand)
- 옵션 아이템 명이 길어지면 가격 밀리는 스타일 수정

## 📝 상세 작업 내용
- [x] 로컬 스토리지 값이 있는 경우 옵션 페이지 기본 설정 값이 바뀌도록 수정
- [x] LNB(Left Navigation Bar)에서도 예상 금액 상태 업데이트 하는 기능
- ~~옵션 아이템 명이 길어지면 가격 밀리는 스타일 수정~~ (#14 반응형 작업에서 같이 하기로 함)

**Comment by redcontroller** [comment]
마지막 Task인,
   **'옵션 아이템 명이 길어지면 가격 밀리는 스타일 수정'**
을 다른 이슈(#14)로 이전하여 해당 이슈를 닫습니다.
