### ISSUE TITLE
🚑 hotfix: 옵션 페이지 새로고침 에러

### ISSUE THREAD

**Issue by ryungom** [NINI-Bros/GENISISU#6]
## 📏구현 및 수정 기능

- 옵션 페이지에서 새로고침 했을 때 서버와 클라이언트 간에 가격이 다르게 인식되는 에러

## 📝 상세 작업 내용
- [x] useLocalStorage 코드 개선하고 에러 다시 확인하기 (서버랑 클라이언트 값 일치시키기)
- [x] 옵션 페이지 vertical 레이아웃 에러 해결 하기
- [x] 옵션 페이지 horizontal 레이아웃 에러 해결 하기
- [x] 옵션 페이지 color 레이아웃 에러 해결 하기

![image](https://github.com/user-attachments/assets/a0bbcfda-1ec2-45bb-a367-0cc9b9ee237c)

**Comment by redcontroller** [comment]
(1) useLocalStorage 코드를 개선하면서 window 객체 인식 안될 때 값이 서버와 초기화 값이 일치되도록 수정함.
(2) 새로고침 시에 'beforeunload' 에 이벤트를 붙여 새로고침을 막고 (e.preventDefault()) 데이터 날리고 진짜 새로고침할 지 묻도록 함
